version: '3.8'
services:
  jmeter:
    build:
      context: ./jmeter
      dockerfile: ./Dockerfile
    image: 'jmeter-docker:latest'
    container_name: jmeter
    restart: always
    hostname: jmeter
    networks:
      - jmeter
    volumes:
      - ./jmeter/output:/results/output
      - ./jmeter/CSV:/CSV
      - ./jmeter/JMX:/JMX
      - ./jmeter/Scripts:/Scripts
    tty: true
    depends_on: 
      - influxdb
      - grafana
      - telegraf
  slave-1:
    build:
      context: ./jmeter
      dockerfile: ./Dockerfile
    image: 'jmeter-docker:latest'
    command: jmeter -s -n -Jclient.rmi.localport=7000 -Jserver.rmi.localport=60000 -Jserver.rmi.ssl.disable=true
    hostname: slave-1
    tty: true
    restart: always
    volumes:
      - ./jmeter/output:/results/output
      - ./jmeter/CSV:/CSV
      - ./jmeter/JMX:/JMX
      - ./jmeter/Scripts:/Scripts      
    networks:
        - jmeter
    depends_on: 
      - jmeter
  slave-2:
    build:
      context: ./jmeter
      dockerfile: ./Dockerfile
    image: 'jmeter-docker:latest'
    command: jmeter -s -n -Jclient.rmi.localport=7000 -Jserver.rmi.localport=60000 -Jserver.rmi.ssl.disable=true
    hostname: slave-2
    tty: true
    restart: always
    volumes:
      - ./jmeter/output:/results/output
      - ./jmeter/CSV:/CSV
      - ./jmeter/JMX:/JMX
      - ./jmeter/Scripts:/Scripts      
    networks:
        - jmeter
    depends_on: 
      - jmeter
networks:
  jmeter: